### ISSUE TITLE
transportoperator documentation

### ISSUE THREAD

**Issue by profseth** [briochemc/AIBECS.jl#81]
According to the current documentation, it's possible to pass the function a value of w (sinking speed) as:
`T = transportoperator(grd; w = 100.0)`

...but that seems to be outdated, as I now hear through the grapevine that transportoperator needs w as a function of z.

**Comment by briochemc** [comment]
Fixed in https://github.com/JuliaOcean/AIBECS.jl/commit/1fd5795eb274d37a2d2f204b55f8e4ded4875873!

Although I think I will deprecate it, you can actually still use a scalar, but it needs to be a simple argument (not a keyword one), as in

```julia
 T = transportoperator(grd, 100.0)
```

Side note: the unit system used is the SI one, so that `100.0` means 100m/s! If you want to use a constant 100m/d settling velocity, I would do

```julia
 T = transportoperator(grd, z -> upreferred(100.0u"m/d"))
```
